/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.61"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    `maven-publish`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {

    implementation("org.web3j:core:4.5.17")

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    testImplementation("org.junit.jupiter:junit-jupiter:5.6.2")
}

tasks.test {
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            groupId = "io.github.cjjavellana"
            artifactId = "armadillo-web3j"
            version = "1.0.0-SNAPSHOT"

            from(components["java"])

            pom {
                name.set("Armadillo Web3j")
                description.set("Web3j With Resiliency Support")
                url.set("https://github.com/cjjavellana/armadillo-web3j")

                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }
                developers {
                    developer {
                        id.set("cjjavellana")
                        name.set("Christian Javellana")
                        email.set("cjjavellana@gmail.com")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com:cjjavellana/armadillo-web3j.git")
                    developerConnection.set("scm:git:ssh://github.com:cjjavellana/armadillo-web3j.git")
                    url.set("https://github.com/cjjavellana/armadillo-web3j")
                }
            }
        }
    }
}

