/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package armadillo.web3j

import kotlin.test.Test
import kotlin.test.assertTrue

class ArmadilloWeb3jTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = ArmadilloWeb3j()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
