/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package armadillo.web3j

import org.web3j.protocol.Web3j

class ArmadilloWeb3j {
    fun someLibraryMethod(): Boolean {
        return true
    }


}
